name: stisp
channels:
  - defaults
dependencies:
  - gdal
  - numpy
  - matplotlib
  - scipy
  - netcdf4
  - spyder
  - pip
  - pandas
  - statsmodels
  - scikit-learn
  - jupyterlab
  - shapely
  - pyshp
  - cartopy